# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-06-14 18:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_squashed_0001_initial'),
    ]

    operations = [
    ]
